version: '3.8'

services:
  backup-service:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - source-postgres
      - target-postgres

  source-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - source_postgres_data:/var/lib/postgresql/data

  target-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - target_postgres_data:/var/lib/postgresql/data

volumes:
  source_postgres_data:
  target_postgres_data: 